version: '3'
services:
  bld:
    image: maven:3.3-jdk-8
    volumes:
      - ./:/usr/src/mymaven
    working_dir: /usr/src/mymaven
    command: mvn clean install

  prod:
    build:
      context: .
      args:
        db_user: devops12
        db_passwd: secret12
        dp_port: 3306
        db_ip: db
        db_name: database
    ports:
      - "80:8080"
    depends_on:
      - bld
      - db
  db:
    image: mariadb:10.1
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: devops12
      MYSQL_PASSWORD: secret12
      MYSQL_DATABASE: database
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  dbdata: