
version: '3'
services:
  bld:
    image: maven:3.3-jdk-8
    volumes:
      - ./:/usr/src/mymaven
    working_dir: /usr/src/mymaven
    command: mvn clean install

  prod:
    image: tomcat:8.0-alpine
    ports:
      - "80:8080"
    depends_on:
      - bld
      - db
    volumes:
      - ./target/App42PaaS-Java-MySQL-Sample-0.0.1-SNAPSHOT.war:/usr/local/tomcat/webapps/App42PaaS.war
      - ./WebContent/Config.properties:/usr/local/tomcat/ROOT/Config.properties
  db:
    image: mariadb:10.1
#    ports:
#    - "8514"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=acp4pogynvaeidfj
      - MYSQL_PASSWORD=jc31d2qyy7h9jv5jn1u9uosjksxzaizw
      - MYSQL_DATABASE=dd
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  dbdata:

